AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - digital.pensieve::PensieveLambda
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  PensieveLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: digital.pensieve.PensieveLambda::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      VpcConfig:
        SecurityGroupIds:
          - sg-be8b4ac0
        SubnetIds:
          - subnet-6bf15e23
          - subnet-8fa052a3
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  PensieveLambdaApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello'
    Export:
      Name: PensieveLambdaApi
